# print("Hello world\n ranjit")
# print("Hello"+" Angela")
# print("Notes from Day 1")
# print("The print statement is used to output strings")
# print("Strings are strings of characters")
# print("String Concatenation is done with the + sign")
# print("New lines can be created with a \ and the letter n")
# input("What is your name?")
# print("Hello "+ input("What is your name?")+"!")
name = input("What is your name?")
length = len(name)
print("Hello "+name +"\nit's length is {length}".format(length=length))
print("Hello "+name +"\nit's length is",length)
print("Hello "+name +'\nit s length is %d' % (length))
print("Hello "+name +'\nit s length is '+ str(length))

# print(length)